server.port: 8081 # Server HTTP port.
# Acquire port
com.cmos.acquire:
    #disable  dataServer and dataHandler .if set this value true,neither dataServer nor dataHandler will work
    disabled: false
   #data server listen on this port
    port: 8000


# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        com.ibatis: DEBUG
        org.hibernate: WARN
        org.springframework: WARN
    file: ipg.log

# Spring settings
spring:
    profiles.active: dev
    datasource:
        max-active: 100
        max-idle: 40
        min-idle: 35
        url: jdbc:mysql://127.0.0.1:3306/jquery?characterEncoding=utf8
        username: root
        password: 123456
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   # Redis
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        database: 0
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1